# Generated by Django 2.2 on 2021-07-24 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wish_app', '0002_auto_20210724_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='granted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='wish',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishes_uploaded', to='wish_app.User'),
        ),
        migrations.DeleteModel(
            name='Granted_Wish',
        ),
    ]
